apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-swarm.yml
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: angular-service
  name: angular-service
spec:
  type: NodePort
  ports:
  - name: "4200"
    port: 4200
    targetPort: 80
  selector:
    io.kompose.service: angular-service
status:
  loadBalancer: {}
