apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-swarm.yml
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: angular-service
  name: angular-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: angular-service
    spec:
      containers:
      - image: evisalumani/mean-angular-nginx:latest
        name: angular-service
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
