# Deploy as: docker-compose -f docker-compse-local.yml up
version: "3"
services:

  # View app at machine-ip:4200
  angular-service:
    # Build image from Dockerfile in this location
    build: ./angular-app
    ports:
      - 4200:80
    depends_on:
      - express-server-service

  express-server-service:
    # Build image from Dockerfile in this location
    build: ./express-server
    ports:
      - 3000:3000
    depends_on:
      - mongo-service

  mongo-service:
    image: mongo:latest
    ports: 
      - 27017:27017