# Deploy as: docker stack deploy -c docker-compose-swarm.yml appName
# Images must be built locally, tagged and then pushed to DockerHub accordingly
version: "3"
services:

  # View app at machine-ip:4200
  angular-service:
    # Build from DockerHub image
    image: my-angular-image:v1
    image: evisalumani/mean-angular-nginx:latest
    ports:
      - 4200:80
    depends_on:
      - express-server-service

  express-server-service:
    # Build from DockerHub image
    image: evisalumani/mean-express:latest
    ports:
      - 3000:3000
    depends_on:
      - mongo-service

  mongo-service:
    image: mongo:latest
    ports: 
      - 27017:27017